-- Inserir template padrão do sistema (protegido)
-- Este template NÃO pode ser editado ou deletado pelos usuários

INSERT INTO contracttemplates (
    id,
    nome,
    descricao,
    tipo,
    conteudo_html,
    eh_padrao,
    ativo,
    company_id,
    variaveis_disponiveis,
    created_at,
    updated_at,
    is_deleted
)
SELECT 
    gen_random_uuid(),
    'Contrato de Prestação de Serviços de Gestão - SISTEMA',
    'Template oficial do sistema para contratos PJ. Este template é protegido e não pode ser editado ou excluído.',
    'PrestacaoServicoPJ',
    pg_read_file('/tmp/template.html')::text,
    true,
    true,
    c.id,
    '["NOME_EMPRESA_CONTRATANTE","CNPJ_CONTRATANTE","ENDERECO_CONTRATANTE","NUMERO_CONTRATANTE","BAIRRO_CONTRATANTE","CIDADE_CONTRATANTE","UF_CONTRATANTE","CEP_CONTRATANTE","ESTADO_REGISTRO_CONTRATANTE","NIRE_CONTRATANTE","NOME_REPRESENTANTE_CONTRATANTE","NACIONALIDADE_REPRESENTANTE","ESTADO_CIVIL_REPRESENTANTE","DATA_NASCIMENTO_REPRESENTANTE","PROFISSAO_REPRESENTANTE","CPF_REPRESENTANTE","RG_REPRESENTANTE","ORGAO_EXPEDIDOR_REPRESENTANTE","ENDERECO_RESIDENCIAL_REPRESENTANTE","NUMERO_RESIDENCIAL_REPRESENTANTE","BAIRRO_RESIDENCIAL_REPRESENTANTE","CIDADE_RESIDENCIAL_REPRESENTANTE","UF_RESIDENCIAL_REPRESENTANTE","CEP_RESIDENCIAL_REPRESENTANTE","RAZAO_SOCIAL_CONTRATADO","CNPJ_CONTRATADO","NOME_CONTRATADO","CPF_CONTRATADO","ENDERECO_CONTRATADO","NUMERO_CONTRATADO","BAIRRO_CONTRATADO","CIDADE_CONTRATADO","ESTADO_CONTRATADO","NACIONALIDADE_CONTRATADO","ESTADO_CIVIL_CONTRATADO","DATA_NASCIMENTO_CONTRATADO","PROFISSAO_CONTRATADO","ENDERECO_RESIDENCIAL_CONTRATADO","NUMERO_RESIDENCIAL_CONTRATADO","BAIRRO_RESIDENCIAL_CONTRATADO","CIDADE_RESIDENCIAL_CONTRATADO","ESTADO_RESIDENCIAL_CONTRATADO","CEP_RESIDENCIAL_CONTRATADO","DATA_PROPOSTA","PRAZO_VIGENCIA","PRAZO_VIGENCIA_EXTENSO","VALOR_MENSAL","VALOR_MENSAL_EXTENSO","VALOR_AJUDA_CUSTO","VALOR_TOTAL_MENSAL","DIA_VENCIMENTO_NF","DIA_VENCIMENTO_NF_EXTENSO","DIA_PAGAMENTO","CIDADE_FORO","ESTADO_FORO","CIDADE_ASSINATURA","DATA_ASSINATURA"]'::jsonb,
    NOW(),
    NOW(),
    false
FROM companies c
WHERE c.id = (SELECT id FROM companies ORDER BY created_at LIMIT 1);

-- Verificar se foi inserido
SELECT id, nome, tipo, eh_padrao, ativo, company_id 
FROM contracttemplates 
WHERE nome LIKE '%SISTEMA%';
